import type { ConfirmedPattern } from './schemaIntelligenceData.js';

type PatternKind = 'exact' | 'family';

function normalizeFieldName(value: string): string {
  return value.toLowerCase().replace(/[^a-z0-9]/g, '');
}

export const COREDIR_ONE_TO_MANY_FIELDS: string[] = [
  'ADDR_LINE1',
  'CUST_NAME',
  'LOAN_MAT_DT',
  'LOAN_INT_RATE',
  'LOAN_OFFICER_NBR',
  'LOAN_TYPE',
  'LOAN_BRANCH_NBR',
  'ACCT_TYPE',
];

const COREDIR_ONE_TO_MANY_SET = new Set(COREDIR_ONE_TO_MANY_FIELDS.map((value) => normalizeFieldName(value)));

export const COREDIR_PICKLIST_TRANSLATIONS: Record<string, Record<string, string>> = {
  LOAN_STATUS: {
    A: 'Active',
    C: 'Closed',
    D: 'Delinquent',
    P: 'Paid Off',
    W: 'Charged Off',
    F: 'Foreclosure',
  },
  ACCT_STATUS: {
    A: 'Active',
    C: 'Closed',
    D: 'Dormant',
    F: 'Frozen',
    O: 'Overdrawn',
  },
  ACCT_TYPE: {
    CK: 'Checking',
    SV: 'Savings',
    CD: 'Certificate of Deposit',
    MM: 'Money Market',
    IRA: 'IRA',
  },
  LOAN_PYMT_FREQ: {
    M: 'Monthly',
    W: 'Weekly',
    B: 'Bi-Weekly',
    S: 'Semi-Monthly',
    Q: 'Quarterly',
    A: 'Annually',
  },
  CUST_TYPE: {
    I: 'Individual',
    B: 'Business',
    T: 'Trust',
    G: 'Government',
  },
  CUST_MARITAL_STATUS: {
    S: 'Single',
    M: 'Married',
    D: 'Divorced',
    W: 'Widowed',
    P: 'Separated',
  },
};

function pattern(
  xmlField: string,
  sfApiName: string,
  sfObject: string,
  kind: PatternKind,
  notes = '',
): ConfirmedPattern {
  return {
    xmlField,
    sfApiNames: [sfApiName],
    sfObject,
    confidence: kind === 'exact' ? 'HIGH' : 'MEDIUM',
    notes,
    isOneToMany: COREDIR_ONE_TO_MANY_SET.has(normalizeFieldName(xmlField)),
    isFormulaTarget: false,
    isPersonAccountOnly: sfApiName.startsWith('Person') || sfApiName.endsWith('__pc'),
  };
}

const RAW_COREDIR_PATTERNS: ConfirmedPattern[] = [
  pattern('CIF_NBR', 'AccountNumber', 'Account', 'exact', 'Core banking CIF number = SF AccountNumber'),
  pattern('CUST_LAST_NAME', 'LastName', 'Account', 'exact'),
  pattern('CUST_FIRST_NAME', 'FirstName', 'Account', 'exact'),
  pattern('CUST_MID_NAME', 'MiddleName', 'Account', 'exact'),
  pattern('CUST_FULL_NAME', 'Name', 'Account', 'exact'),
  pattern('CUST_TITLE', 'Salutation', 'Account', 'family', 'Title → Salutation picklist'),
  pattern('CUST_SUFFIX', 'Suffix__pc', 'Account', 'exact'),
  pattern('CUST_DOB', 'PersonBirthdate', 'Account', 'exact', 'DOB = Date Of Birth'),
  pattern('CUST_DATE_OF_BIRTH', 'PersonBirthdate', 'Account', 'exact'),
  pattern('CUST_SSN', 'SIN_SSN__pc', 'Account', 'exact', 'SSN → PII field; compliance tag PII required'),
  pattern('CUST_SSN_TIN', 'SIN_SSN__pc', 'Account', 'exact'),
  pattern('CUST_TAX_ID', 'SIN_SSN__pc', 'Account', 'family'),
  pattern('CUST_TYPE', 'FinServ__IndividualType__c', 'Account', 'family', 'I=Individual, B=Business'),
  pattern('CUST_MARITAL_STATUS', 'FinServ__MaritalStatus__pc', 'Account', 'exact'),
  pattern('CUST_CITIZENSHIP', 'FinServ__Citizenship__pc', 'Account', 'exact'),
  pattern('CUST_COUNTRY', 'FinServ__CountryOfResidence__pc', 'Account', 'family'),
  pattern('CUST_EMAIL', 'PersonEmail', 'Account', 'exact'),
  pattern('CUST_EMAIL_ADDR', 'PersonEmail', 'Account', 'exact'),
  pattern('CUST_HOME_PHONE', 'PersonHomePhone', 'Account', 'exact'),
  pattern('CUST_WORK_PHONE', 'PersonOtherPhone', 'Account', 'exact', 'Work phone → OtherPhone'),
  pattern('CUST_CELL_PHONE', 'PersonMobilePhone', 'Account', 'exact'),
  pattern('CUST_FAX', 'Fax', 'Account', 'exact'),
  pattern('ADDR_LINE1', 'BillingStreet', 'Account', 'exact', 'Also PersonMailingStreet for person accounts'),
  pattern('ADDR_LINE2', 'BillingStreet', 'Account', 'exact', 'Append to ADDR_LINE1 with newline'),
  pattern('CUST_CITY', 'BillingCity', 'Account', 'exact'),
  pattern('CUST_STATE', 'BillingState', 'Account', 'exact'),
  pattern('CUST_ZIP', 'BillingPostalCode', 'Account', 'exact'),
  pattern('CUST_ZIP_CODE', 'BillingPostalCode', 'Account', 'exact'),
  pattern('CUST_COUNTRY_CODE', 'BillingCountryCode', 'Account', 'exact'),

  pattern('EMPL_EMPLOYER_NAME', 'FinServ__Employer__pc', 'Account', 'exact'),
  pattern('EMPL_STATUS', 'FinServ__EmploymentStatus__pc', 'Account', 'exact'),
  pattern('EMPL_OCCUPATION', 'FinServ__Occupation__pc', 'Account', 'exact'),
  pattern('EMPL_ANNUAL_INCOME', 'Annual_Income__c', 'Account', 'exact'),
  pattern('EMPL_MONTHLY_INCOME', 'Salary_Total_Monthly_Amount__c', 'PIT', 'family', 'Monthly income → Party Involved in Transaction'),
  pattern('EMPL_YEARS', 'FinServ__YearsAtCurrentEmployer__pc', 'Account', 'exact'),

  pattern('LOAN_NBR', 'Loan_Number__c', 'Loan', 'exact'),
  pattern('LOAN_NUMBER', 'Loan_Number__c', 'Loan', 'exact'),
  pattern('LOAN_BAL', 'FinServ__Balance__c', 'FinancialAccount', 'exact', 'Post-boarding: Financial Account. Pre-boarding: calculated field on Loan'),
  pattern('LOAN_BALANCE', 'FinServ__Balance__c', 'FinancialAccount', 'exact'),
  pattern('LOAN_PRIN_BAL', 'FinServ__PrincipalBalance__c', 'FinancialAccount', 'exact'),
  pattern('LOAN_PRINCIPAL_BAL', 'FinServ__PrincipalBalance__c', 'FinancialAccount', 'exact'),
  pattern('LOAN_ORG_AMT', 'FinServ__LoanAmount__c', 'FinancialAccount', 'exact', 'Original/origination amount = LoanAmount'),
  pattern('LOAN_ORIG_AMT', 'FinServ__LoanAmount__c', 'FinancialAccount', 'exact'),
  pattern('LOAN_ORIGINAL_AMT', 'FinServ__LoanAmount__c', 'FinancialAccount', 'exact'),
  pattern('LOAN_INT_RATE', 'FinServ__InterestRate__c', 'FinancialAccount', 'exact', 'Pre-boarding → AnnualInterestRate__c on Loan; post-boarding → FSC field'),
  pattern('LOAN_INTEREST_RATE', 'FinServ__InterestRate__c', 'FinancialAccount', 'exact'),
  pattern('LOAN_OPEN_DT', 'FinServ__OpenDate__c', 'FinancialAccount', 'exact'),
  pattern('LOAN_OPEN_DATE', 'FinServ__OpenDate__c', 'FinancialAccount', 'exact'),
  pattern('LOAN_MAT_DT', 'FinServ__LoanEndDate__c', 'FinancialAccount', 'exact', 'Maturity = loan end date'),
  pattern('LOAN_MATURITY_DT', 'FinServ__LoanEndDate__c', 'FinancialAccount', 'exact'),
  pattern('LOAN_MATURITY_DATE', 'FinServ__LoanEndDate__c', 'FinancialAccount', 'exact'),
  pattern('LOAN_CLOSE_DT', 'FinServ__CloseDate__c', 'FinancialAccount', 'exact'),
  pattern('LOAN_PYMT_AMT', 'FinServ__PaymentAmount__c', 'FinancialAccount', 'exact'),
  pattern('LOAN_PAYMENT_AMT', 'FinServ__PaymentAmount__c', 'FinancialAccount', 'exact'),
  pattern('LOAN_PYMT_FREQ', 'FinServ__PaymentFrequency__c', 'FinancialAccount', 'exact', 'M=Monthly, W=Weekly, B=Bi-weekly → FSC picklist translation required'),
  pattern('LOAN_PAYMENT_FREQ', 'FinServ__PaymentFrequency__c', 'FinancialAccount', 'exact'),
  pattern('LOAN_NEXT_PYMT_DT', 'FinServ__NextPaymentDate__c', 'FinancialAccount', 'exact'),
  pattern('LOAN_NEXT_DUE_DT', 'FinServ__NextPaymentDate__c', 'FinancialAccount', 'family'),
  pattern('LOAN_PAST_DUE_AMT', 'Amount_Past_Due__c', 'FinancialAccount', 'exact'),
  pattern('LOAN_PAST_DUE_DAYS', 'FinServ__DaysLate__c', 'FinancialAccount', 'family'),
  pattern('LOAN_DAYS_LATE', 'FinServ__DaysLate__c', 'FinancialAccount', 'exact'),
  pattern('LOAN_STATUS', 'Account_Status__c', 'FinancialAccount', 'exact', 'A=Active, C=Closed, D=Delinquent'),
  pattern('LOAN_STATUS_CD', 'Account_Status__c', 'FinancialAccount', 'exact'),
  pattern('LOAN_TYPE', 'FinServ__FinancialAccountType__c', 'FinancialAccount', 'family'),
  pattern('LOAN_TYPE_CD', 'Type_Code__c', 'Loan', 'exact'),
  pattern('GL_ACCT', 'GL_Code__c', 'FinancialAccount', 'exact'),
  pattern('LOAN_GL_ACCT', 'GL_Code__c', 'FinancialAccount', 'exact'),
  pattern('LOAN_GL_CODE', 'GL_Code__c', 'FinancialAccount', 'exact'),
  pattern('LOAN_BRANCH_NBR', 'FinServ__BranchCode__c', 'FinancialAccount', 'exact', 'Branch number → BranchCode; name resolution needed for BranchName'),
  pattern('LOAN_BRANCH_CD', 'FinServ__BranchCode__c', 'FinancialAccount', 'exact'),
  pattern('LOAN_OFFICER_NBR', 'OwnerId', 'FinancialAccount', 'family', 'Loan officer number → User lookup; number-to-User-ID resolution required'),
  pattern('LOAN_OFFICER_ID', 'OwnerId', 'FinancialAccount', 'family'),
  pattern('LOAN_RISK_RATING', 'Risk_Code__c', 'Loan', 'exact'),
  pattern('LOAN_RISK_CD', 'Risk_Code__c', 'Loan', 'exact'),
  pattern('LOAN_PURPOSE', 'Loan_Purpose__c', 'Loan', 'exact'),
  pattern('LOAN_PURPOSE_CD', 'Loan_Purpose__c', 'Loan', 'exact'),
  pattern('LOAN_ESCROW_AMT', 'Escrow_Amount__c', 'FinancialAccount', 'exact'),
  pattern('LOAN_ESCROW_BAL', 'Escrow_Amount__c', 'FinancialAccount', 'exact'),
  pattern('LOAN_TERM_MONTHS', 'TermInMonth__c', 'Loan', 'exact'),
  pattern('LOAN_NUM_PAYMENTS', 'Number_of_Payments__c', 'Loan', 'exact'),
  pattern('LOAN_CREDIT_LIMIT', 'Credit_Limit__c', 'Loan', 'exact'),
  pattern('LOAN_INT_YTD', 'Interest_YTD__c', 'FinancialAccount', 'family', 'Interest year-to-date'),
  pattern('LOAN_ACCR_INT', 'FinServ__AccruedInterest__c', 'FinancialAccount', 'family', 'Accrued interest'),
  pattern('LOAN_BOARD_DT', 'Inserted_In_Core__c', 'Loan', 'exact', 'Board date = core banking posting date; same semantic as BOSL DATE_BOARDING'),
  pattern('LOAN_BOARDED_DT', 'Inserted_In_Core__c', 'Loan', 'exact'),
  pattern('LOAN_APPL_DT', 'FinServ__ApplicationDate__c', 'FinancialAccount', 'exact'),
  pattern('LOAN_APP_DT', 'FinServ__ApplicationDate__c', 'FinancialAccount', 'exact'),
  pattern('LOAN_APPRVL_DT', 'Date_Credit_Approved__c', 'FinancialAccount', 'exact'),
  pattern('LOAN_APPROVAL_DT', 'Date_Credit_Approved__c', 'FinancialAccount', 'exact'),

  pattern('ACCT_NBR', 'FinServ__FinancialAccountNumber__c', 'FinancialAccount', 'exact'),
  pattern('ACCT_NUMBER', 'FinServ__FinancialAccountNumber__c', 'FinancialAccount', 'exact'),
  pattern('ACCT_BAL', 'FinServ__Balance__c', 'FinancialAccount', 'exact'),
  pattern('ACCT_BALANCE', 'FinServ__Balance__c', 'FinancialAccount', 'exact'),
  pattern('ACCT_AVAIL_BAL', 'FinServ__AvailableBalance__c', 'FinancialAccount', 'exact'),
  pattern('ACCT_INT_RATE', 'FinServ__InterestRate__c', 'FinancialAccount', 'exact'),
  pattern('ACCT_OPEN_DT', 'FinServ__OpenDate__c', 'FinancialAccount', 'exact'),
  pattern('ACCT_CLOSE_DT', 'FinServ__CloseDate__c', 'FinancialAccount', 'exact'),
  pattern('ACCT_STATUS', 'Account_Status__c', 'FinancialAccount', 'exact'),
  pattern('ACCT_STATUS_CD', 'Account_Status__c', 'FinancialAccount', 'exact'),
  pattern('ACCT_TYPE', 'FinServ__FinancialAccountType__c', 'FinancialAccount', 'exact', 'CK=Checking, SV=Savings, CD=Certificate of Deposit, MM=Money Market'),
  pattern('ACCT_TYPE_CD', 'FinServ__FinancialAccountType__c', 'FinancialAccount', 'exact'),
  pattern('ACCT_BRANCH_NBR', 'FinServ__BranchCode__c', 'FinancialAccount', 'exact'),
  pattern('ACCT_OFFICER_NBR', 'OwnerId', 'FinancialAccount', 'family'),

  pattern('COL_TYPE', 'Asset_Type__c', 'Collateral', 'exact'),
  pattern('COL_TYPE_CD', 'Asset_Type__c', 'Collateral', 'exact'),
  pattern('COL_VALUE', 'Amount_Financed__c', 'Collateral', 'family'),
  pattern('COL_APPRAISED_VALUE', 'Amount_Financed__c', 'Collateral', 'exact'),
  pattern('COL_FORCED_VALUE', 'Forced_Sale_Value_Calculated__c', 'Collateral', 'exact'),
  pattern('COL_DESC', 'Name', 'Collateral', 'family', 'Collateral description → Name field'),
  pattern('COL_LIEN_POS', 'Lien_Position__c', 'Collateral', 'family'),

  pattern('LIAB_INSTITUTION', 'Institution_Bank_Held_c__c', 'PartyLiabilities', 'exact'),
  pattern('LIAB_BALANCE', 'Amount_Owed__c', 'PartyLiabilities', 'exact'),
  pattern('LIAB_MONTHLY_PYMT', 'Monthly_Payment_Amount__c', 'PartyLiabilities', 'family'),
  pattern('LIAB_ACCT_NBR', 'Account_Number__c', 'PartyLiabilities', 'exact'),

  pattern('CIF_NUMBER', 'AccountNumber', 'Account', 'family', 'Alias of CIF_NBR.'),
  pattern('CIF_NO', 'AccountNumber', 'Account', 'family', 'Alias of CIF_NBR.'),
  pattern('CUST_LAST_NM', 'LastName', 'Account', 'family', 'Alias of CUST_LAST_NAME.'),
  pattern('CUST_FIRST_NM', 'FirstName', 'Account', 'family', 'Alias of CUST_FIRST_NAME.'),
  pattern('CUST_MIDDLE_NAME', 'MiddleName', 'Account', 'family', 'Alias of CUST_MID_NAME.'),
  pattern('CUST_MID_INITIAL', 'MiddleName', 'Account', 'family', 'Middle initial stored in middle-name field.'),
  pattern('CUST_HOME_PHONE_NBR', 'PersonHomePhone', 'Account', 'family', 'Alias of CUST_HOME_PHONE.'),
  pattern('CUST_WORK_PHONE_NBR', 'PersonOtherPhone', 'Account', 'family', 'Alias of CUST_WORK_PHONE.'),
  pattern('CUST_MOBILE_PHONE', 'PersonMobilePhone', 'Account', 'family', 'Alias of CUST_CELL_PHONE.'),
  pattern('CUST_EMAIL_ADDRESS', 'PersonEmail', 'Account', 'family', 'Alias of CUST_EMAIL_ADDR.'),
  pattern('CUST_ADDR_LINE1', 'BillingStreet', 'Account', 'family', 'Alias of ADDR_LINE1.'),
  pattern('CUST_ADDR_LINE2', 'BillingStreet', 'Account', 'family', 'Alias of ADDR_LINE2.'),
  pattern('CUST_POSTAL_CODE', 'BillingPostalCode', 'Account', 'family', 'Alias of CUST_ZIP_CODE.'),
  pattern('CUST_RES_COUNTRY', 'FinServ__CountryOfResidence__pc', 'Account', 'family', 'Alias of CUST_COUNTRY.'),
  pattern('EMPL_EMPLOYER', 'FinServ__Employer__pc', 'Account', 'family', 'Alias of EMPL_EMPLOYER_NAME.'),
  pattern('EMPL_ANNUAL_INC', 'Annual_Income__c', 'Account', 'family', 'Alias of EMPL_ANNUAL_INCOME.'),
  pattern('EMPL_MONTHLY_INC', 'Salary_Total_Monthly_Amount__c', 'PIT', 'family', 'Alias of EMPL_MONTHLY_INCOME.'),
  pattern('LOAN_NO', 'Loan_Number__c', 'Loan', 'family', 'Alias of LOAN_NBR.'),
  pattern('LOAN_BAL_AMT', 'FinServ__Balance__c', 'FinancialAccount', 'family', 'Alias of LOAN_BAL.'),
  pattern('LOAN_PMT_AMT', 'FinServ__PaymentAmount__c', 'FinancialAccount', 'family', 'Alias of LOAN_PYMT_AMT.'),
  pattern('LOAN_PMT_FREQ_CD', 'FinServ__PaymentFrequency__c', 'FinancialAccount', 'family', 'Alias of LOAN_PYMT_FREQ.'),
  pattern('LOAN_NEXT_PMT_DT', 'FinServ__NextPaymentDate__c', 'FinancialAccount', 'family', 'Alias of LOAN_NEXT_PYMT_DT.'),
  pattern('LOAN_BRANCH_NO', 'FinServ__BranchCode__c', 'FinancialAccount', 'family', 'Alias of LOAN_BRANCH_NBR.'),
  pattern('LOAN_OFFICER_NO', 'OwnerId', 'FinancialAccount', 'family', 'Alias of LOAN_OFFICER_NBR.'),
  pattern('LOAN_APRVL_DT', 'Date_Credit_Approved__c', 'FinancialAccount', 'family', 'Alias of LOAN_APPRVL_DT.'),
  pattern('LOAN_ORIGINATION_AMT', 'FinServ__LoanAmount__c', 'FinancialAccount', 'family', 'Alias of LOAN_ORIGINAL_AMT.'),
  pattern('LOAN_TERM_MTHS', 'TermInMonth__c', 'Loan', 'family', 'Alias of LOAN_TERM_MONTHS.'),
  pattern('DEP_NBR', 'FinServ__FinancialAccountNumber__c', 'FinancialAccount', 'family', 'Deposit-account alias of ACCT_NBR.'),
  pattern('DEP_BAL', 'FinServ__Balance__c', 'FinancialAccount', 'family', 'Deposit-account alias of ACCT_BAL.'),
  pattern('DEP_AVAIL_BAL', 'FinServ__AvailableBalance__c', 'FinancialAccount', 'family', 'Deposit-account alias of ACCT_AVAIL_BAL.'),
  pattern('DEP_INT_RATE', 'FinServ__InterestRate__c', 'FinancialAccount', 'family', 'Deposit-account alias of ACCT_INT_RATE.'),
  pattern('DEP_OPEN_DT', 'FinServ__OpenDate__c', 'FinancialAccount', 'family', 'Deposit-account alias of ACCT_OPEN_DT.'),
  pattern('DEP_STATUS', 'Account_Status__c', 'FinancialAccount', 'family', 'Deposit-account alias of ACCT_STATUS.'),
  pattern('DEP_TYPE', 'FinServ__FinancialAccountType__c', 'FinancialAccount', 'family', 'Deposit-account alias of ACCT_TYPE.'),
  pattern('COLL_TYPE', 'Asset_Type__c', 'Collateral', 'family', 'Alias of COL_TYPE.'),
  pattern('COLL_DESC', 'Name', 'Collateral', 'family', 'Alias of COL_DESC.'),
  pattern('LIAB_MONTHLY_PAYMENT', 'Monthly_Payment_Amount__c', 'PartyLiabilities', 'family', 'Alias of LIAB_MONTHLY_PYMT.'),
  pattern('LIAB_BANK_NAME', 'Institution_Bank_Held_c__c', 'PartyLiabilities', 'family', 'Alias of LIAB_INSTITUTION.'),
];

export const COREDIR_FSC_PATTERNS: Record<string, ConfirmedPattern[]> = RAW_COREDIR_PATTERNS.reduce<Record<string, ConfirmedPattern[]>>((acc, entry) => {
  const key = normalizeFieldName(entry.xmlField);
  if (!acc[key]) {
    acc[key] = [];
  }
  acc[key].push(entry);
  return acc;
}, {});
